# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  #
	#	TODO:
	# [ ] Network configuration -> bridged
	# [ ] Host names!
	#

  config.vm.define "worker" do |worker|
		worker.vm.network "private_network", ip: "192.168.33.10"
		worker.vm.synced_folder "../", "/project"
		worker.vm.provision "shell", path: "worker.sh"
	end

	config.vm.define "service" do |service|
		service.vm.network "private_network", ip: "192.168.33.20"
		service.vm.synced_folder "../", "/project"
		service.vm.provision "shell", path: "service.sh"
	end
end
